/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SiteRouteImport } from './routes/_site'
import { Route as SiteIndexRouteImport } from './routes/_site/index'
import { Route as SitePrivacyRouteImport } from './routes/_site/privacy'
import { Route as SiteImprintRouteImport } from './routes/_site/imprint'
import { Route as SiteGatedRouteImport } from './routes/_site/_gated'
import { Route as SiteGatedNewsRouteImport } from './routes/_site/_gated/news'
import { Route as SiteGatedJoinRouteImport } from './routes/_site/_gated/join'
import { Route as SiteGatedGalleryRouteImport } from './routes/_site/_gated/gallery'
import { Route as SiteGatedEventsRouteImport } from './routes/_site/_gated/events'
import { Route as SiteGatedClubRouteImport } from './routes/_site/_gated/club'
import { Route as SiteGatedNewsSlugRouteImport } from './routes/_site/_gated/news_.$slug'
import { Route as SiteGatedJoinApplyRouteImport } from './routes/_site/_gated/join_.apply'
import { Route as SiteGatedGalleryAlbumSlugRouteImport } from './routes/_site/_gated/gallery_.$albumSlug'
import { Route as SiteGatedEventsExchangeRouteImport } from './routes/_site/_gated/events_.exchange'
import { Route as SiteGatedEventsEventSlugRouteImport } from './routes/_site/_gated/events_.$eventSlug'
import { Route as SiteGatedEventsEventSlugSeatsRouteImport } from './routes/_site/_gated/events_.$eventSlug_.seats'

const SiteRoute = SiteRouteImport.update({
  id: '/_site',
  getParentRoute: () => rootRouteImport,
} as any)
const SiteIndexRoute = SiteIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => SiteRoute,
} as any)
const SitePrivacyRoute = SitePrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => SiteRoute,
} as any)
const SiteImprintRoute = SiteImprintRouteImport.update({
  id: '/imprint',
  path: '/imprint',
  getParentRoute: () => SiteRoute,
} as any)
const SiteGatedRoute = SiteGatedRouteImport.update({
  id: '/_gated',
  getParentRoute: () => SiteRoute,
} as any)
const SiteGatedNewsRoute = SiteGatedNewsRouteImport.update({
  id: '/news',
  path: '/news',
  getParentRoute: () => SiteGatedRoute,
} as any)
const SiteGatedJoinRoute = SiteGatedJoinRouteImport.update({
  id: '/join',
  path: '/join',
  getParentRoute: () => SiteGatedRoute,
} as any)
const SiteGatedGalleryRoute = SiteGatedGalleryRouteImport.update({
  id: '/gallery',
  path: '/gallery',
  getParentRoute: () => SiteGatedRoute,
} as any)
const SiteGatedEventsRoute = SiteGatedEventsRouteImport.update({
  id: '/events',
  path: '/events',
  getParentRoute: () => SiteGatedRoute,
} as any)
const SiteGatedClubRoute = SiteGatedClubRouteImport.update({
  id: '/club',
  path: '/club',
  getParentRoute: () => SiteGatedRoute,
} as any)
const SiteGatedNewsSlugRoute = SiteGatedNewsSlugRouteImport.update({
  id: '/news_/$slug',
  path: '/news/$slug',
  getParentRoute: () => SiteGatedRoute,
} as any)
const SiteGatedJoinApplyRoute = SiteGatedJoinApplyRouteImport.update({
  id: '/join_/apply',
  path: '/join/apply',
  getParentRoute: () => SiteGatedRoute,
} as any)
const SiteGatedGalleryAlbumSlugRoute =
  SiteGatedGalleryAlbumSlugRouteImport.update({
    id: '/gallery_/$albumSlug',
    path: '/gallery/$albumSlug',
    getParentRoute: () => SiteGatedRoute,
  } as any)
const SiteGatedEventsExchangeRoute = SiteGatedEventsExchangeRouteImport.update({
  id: '/events_/exchange',
  path: '/events/exchange',
  getParentRoute: () => SiteGatedRoute,
} as any)
const SiteGatedEventsEventSlugRoute =
  SiteGatedEventsEventSlugRouteImport.update({
    id: '/events_/$eventSlug',
    path: '/events/$eventSlug',
    getParentRoute: () => SiteGatedRoute,
  } as any)
const SiteGatedEventsEventSlugSeatsRoute =
  SiteGatedEventsEventSlugSeatsRouteImport.update({
    id: '/events_/$eventSlug_/seats',
    path: '/events/$eventSlug/seats',
    getParentRoute: () => SiteGatedRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof SiteIndexRoute
  '/imprint': typeof SiteImprintRoute
  '/privacy': typeof SitePrivacyRoute
  '/club': typeof SiteGatedClubRoute
  '/events': typeof SiteGatedEventsRoute
  '/gallery': typeof SiteGatedGalleryRoute
  '/join': typeof SiteGatedJoinRoute
  '/news': typeof SiteGatedNewsRoute
  '/events/$eventSlug': typeof SiteGatedEventsEventSlugRoute
  '/events/exchange': typeof SiteGatedEventsExchangeRoute
  '/gallery/$albumSlug': typeof SiteGatedGalleryAlbumSlugRoute
  '/join/apply': typeof SiteGatedJoinApplyRoute
  '/news/$slug': typeof SiteGatedNewsSlugRoute
  '/events/$eventSlug/seats': typeof SiteGatedEventsEventSlugSeatsRoute
}
export interface FileRoutesByTo {
  '/': typeof SiteIndexRoute
  '/imprint': typeof SiteImprintRoute
  '/privacy': typeof SitePrivacyRoute
  '/club': typeof SiteGatedClubRoute
  '/events': typeof SiteGatedEventsRoute
  '/gallery': typeof SiteGatedGalleryRoute
  '/join': typeof SiteGatedJoinRoute
  '/news': typeof SiteGatedNewsRoute
  '/events/$eventSlug': typeof SiteGatedEventsEventSlugRoute
  '/events/exchange': typeof SiteGatedEventsExchangeRoute
  '/gallery/$albumSlug': typeof SiteGatedGalleryAlbumSlugRoute
  '/join/apply': typeof SiteGatedJoinApplyRoute
  '/news/$slug': typeof SiteGatedNewsSlugRoute
  '/events/$eventSlug/seats': typeof SiteGatedEventsEventSlugSeatsRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_site': typeof SiteRouteWithChildren
  '/_site/_gated': typeof SiteGatedRouteWithChildren
  '/_site/imprint': typeof SiteImprintRoute
  '/_site/privacy': typeof SitePrivacyRoute
  '/_site/': typeof SiteIndexRoute
  '/_site/_gated/club': typeof SiteGatedClubRoute
  '/_site/_gated/events': typeof SiteGatedEventsRoute
  '/_site/_gated/gallery': typeof SiteGatedGalleryRoute
  '/_site/_gated/join': typeof SiteGatedJoinRoute
  '/_site/_gated/news': typeof SiteGatedNewsRoute
  '/_site/_gated/events_/$eventSlug': typeof SiteGatedEventsEventSlugRoute
  '/_site/_gated/events_/exchange': typeof SiteGatedEventsExchangeRoute
  '/_site/_gated/gallery_/$albumSlug': typeof SiteGatedGalleryAlbumSlugRoute
  '/_site/_gated/join_/apply': typeof SiteGatedJoinApplyRoute
  '/_site/_gated/news_/$slug': typeof SiteGatedNewsSlugRoute
  '/_site/_gated/events_/$eventSlug_/seats': typeof SiteGatedEventsEventSlugSeatsRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/imprint'
    | '/privacy'
    | '/club'
    | '/events'
    | '/gallery'
    | '/join'
    | '/news'
    | '/events/$eventSlug'
    | '/events/exchange'
    | '/gallery/$albumSlug'
    | '/join/apply'
    | '/news/$slug'
    | '/events/$eventSlug/seats'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/imprint'
    | '/privacy'
    | '/club'
    | '/events'
    | '/gallery'
    | '/join'
    | '/news'
    | '/events/$eventSlug'
    | '/events/exchange'
    | '/gallery/$albumSlug'
    | '/join/apply'
    | '/news/$slug'
    | '/events/$eventSlug/seats'
  id:
    | '__root__'
    | '/_site'
    | '/_site/_gated'
    | '/_site/imprint'
    | '/_site/privacy'
    | '/_site/'
    | '/_site/_gated/club'
    | '/_site/_gated/events'
    | '/_site/_gated/gallery'
    | '/_site/_gated/join'
    | '/_site/_gated/news'
    | '/_site/_gated/events_/$eventSlug'
    | '/_site/_gated/events_/exchange'
    | '/_site/_gated/gallery_/$albumSlug'
    | '/_site/_gated/join_/apply'
    | '/_site/_gated/news_/$slug'
    | '/_site/_gated/events_/$eventSlug_/seats'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  SiteRoute: typeof SiteRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_site': {
      id: '/_site'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof SiteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_site/': {
      id: '/_site/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof SiteIndexRouteImport
      parentRoute: typeof SiteRoute
    }
    '/_site/privacy': {
      id: '/_site/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof SitePrivacyRouteImport
      parentRoute: typeof SiteRoute
    }
    '/_site/imprint': {
      id: '/_site/imprint'
      path: '/imprint'
      fullPath: '/imprint'
      preLoaderRoute: typeof SiteImprintRouteImport
      parentRoute: typeof SiteRoute
    }
    '/_site/_gated': {
      id: '/_site/_gated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof SiteGatedRouteImport
      parentRoute: typeof SiteRoute
    }
    '/_site/_gated/news': {
      id: '/_site/_gated/news'
      path: '/news'
      fullPath: '/news'
      preLoaderRoute: typeof SiteGatedNewsRouteImport
      parentRoute: typeof SiteGatedRoute
    }
    '/_site/_gated/join': {
      id: '/_site/_gated/join'
      path: '/join'
      fullPath: '/join'
      preLoaderRoute: typeof SiteGatedJoinRouteImport
      parentRoute: typeof SiteGatedRoute
    }
    '/_site/_gated/gallery': {
      id: '/_site/_gated/gallery'
      path: '/gallery'
      fullPath: '/gallery'
      preLoaderRoute: typeof SiteGatedGalleryRouteImport
      parentRoute: typeof SiteGatedRoute
    }
    '/_site/_gated/events': {
      id: '/_site/_gated/events'
      path: '/events'
      fullPath: '/events'
      preLoaderRoute: typeof SiteGatedEventsRouteImport
      parentRoute: typeof SiteGatedRoute
    }
    '/_site/_gated/club': {
      id: '/_site/_gated/club'
      path: '/club'
      fullPath: '/club'
      preLoaderRoute: typeof SiteGatedClubRouteImport
      parentRoute: typeof SiteGatedRoute
    }
    '/_site/_gated/news_/$slug': {
      id: '/_site/_gated/news_/$slug'
      path: '/news/$slug'
      fullPath: '/news/$slug'
      preLoaderRoute: typeof SiteGatedNewsSlugRouteImport
      parentRoute: typeof SiteGatedRoute
    }
    '/_site/_gated/join_/apply': {
      id: '/_site/_gated/join_/apply'
      path: '/join/apply'
      fullPath: '/join/apply'
      preLoaderRoute: typeof SiteGatedJoinApplyRouteImport
      parentRoute: typeof SiteGatedRoute
    }
    '/_site/_gated/gallery_/$albumSlug': {
      id: '/_site/_gated/gallery_/$albumSlug'
      path: '/gallery/$albumSlug'
      fullPath: '/gallery/$albumSlug'
      preLoaderRoute: typeof SiteGatedGalleryAlbumSlugRouteImport
      parentRoute: typeof SiteGatedRoute
    }
    '/_site/_gated/events_/exchange': {
      id: '/_site/_gated/events_/exchange'
      path: '/events/exchange'
      fullPath: '/events/exchange'
      preLoaderRoute: typeof SiteGatedEventsExchangeRouteImport
      parentRoute: typeof SiteGatedRoute
    }
    '/_site/_gated/events_/$eventSlug': {
      id: '/_site/_gated/events_/$eventSlug'
      path: '/events/$eventSlug'
      fullPath: '/events/$eventSlug'
      preLoaderRoute: typeof SiteGatedEventsEventSlugRouteImport
      parentRoute: typeof SiteGatedRoute
    }
    '/_site/_gated/events_/$eventSlug_/seats': {
      id: '/_site/_gated/events_/$eventSlug_/seats'
      path: '/events/$eventSlug/seats'
      fullPath: '/events/$eventSlug/seats'
      preLoaderRoute: typeof SiteGatedEventsEventSlugSeatsRouteImport
      parentRoute: typeof SiteGatedRoute
    }
  }
}

interface SiteGatedRouteChildren {
  SiteGatedClubRoute: typeof SiteGatedClubRoute
  SiteGatedEventsRoute: typeof SiteGatedEventsRoute
  SiteGatedGalleryRoute: typeof SiteGatedGalleryRoute
  SiteGatedJoinRoute: typeof SiteGatedJoinRoute
  SiteGatedNewsRoute: typeof SiteGatedNewsRoute
  SiteGatedEventsEventSlugRoute: typeof SiteGatedEventsEventSlugRoute
  SiteGatedEventsExchangeRoute: typeof SiteGatedEventsExchangeRoute
  SiteGatedGalleryAlbumSlugRoute: typeof SiteGatedGalleryAlbumSlugRoute
  SiteGatedJoinApplyRoute: typeof SiteGatedJoinApplyRoute
  SiteGatedNewsSlugRoute: typeof SiteGatedNewsSlugRoute
  SiteGatedEventsEventSlugSeatsRoute: typeof SiteGatedEventsEventSlugSeatsRoute
}

const SiteGatedRouteChildren: SiteGatedRouteChildren = {
  SiteGatedClubRoute: SiteGatedClubRoute,
  SiteGatedEventsRoute: SiteGatedEventsRoute,
  SiteGatedGalleryRoute: SiteGatedGalleryRoute,
  SiteGatedJoinRoute: SiteGatedJoinRoute,
  SiteGatedNewsRoute: SiteGatedNewsRoute,
  SiteGatedEventsEventSlugRoute: SiteGatedEventsEventSlugRoute,
  SiteGatedEventsExchangeRoute: SiteGatedEventsExchangeRoute,
  SiteGatedGalleryAlbumSlugRoute: SiteGatedGalleryAlbumSlugRoute,
  SiteGatedJoinApplyRoute: SiteGatedJoinApplyRoute,
  SiteGatedNewsSlugRoute: SiteGatedNewsSlugRoute,
  SiteGatedEventsEventSlugSeatsRoute: SiteGatedEventsEventSlugSeatsRoute,
}

const SiteGatedRouteWithChildren = SiteGatedRoute._addFileChildren(
  SiteGatedRouteChildren,
)

interface SiteRouteChildren {
  SiteGatedRoute: typeof SiteGatedRouteWithChildren
  SiteImprintRoute: typeof SiteImprintRoute
  SitePrivacyRoute: typeof SitePrivacyRoute
  SiteIndexRoute: typeof SiteIndexRoute
}

const SiteRouteChildren: SiteRouteChildren = {
  SiteGatedRoute: SiteGatedRouteWithChildren,
  SiteImprintRoute: SiteImprintRoute,
  SitePrivacyRoute: SitePrivacyRoute,
  SiteIndexRoute: SiteIndexRoute,
}

const SiteRouteWithChildren = SiteRoute._addFileChildren(SiteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  SiteRoute: SiteRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
