// <auto-generated />
using System;
using Furria.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Furria.Infrastructure.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260925184204_ClubRecord")]
    partial class ClubRecord
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Furria.Core.Club.Announcement", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("AuthorPersonId")
                        .HasColumnType("integer")
                        .HasColumnName("author_person_id");

                    b.Property<string>("Body")
                        .IsRequired()
                        .HasMaxLength(4000)
                        .HasColumnType("character varying(4000)")
                        .HasColumnName("body");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<DateTimeOffset>("PublishedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("published_at");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)")
                        .HasColumnName("title");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at")
                        .HasDefaultValueSql("now()");

                    b.Property<DateOnly?>("ValidUntil")
                        .HasColumnType("date")
                        .HasColumnName("valid_until");

                    b.HasKey("Id")
                        .HasName("pk_announcement");

                    b.HasIndex("AuthorPersonId")
                        .HasDatabaseName("ix_announcement_author_person_id");

                    b.HasIndex("PublishedAt")
                        .HasDatabaseName("ix_announcement_published_at");

                    b.ToTable("announcement", (string)null);
                });

            modelBuilder.Entity("Furria.Core.Club.AttendanceResponse", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Answer")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("answer");

                    b.Property<int>("CalendarEntryId")
                        .HasColumnType("integer")
                        .HasColumnName("calendar_entry_id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<int>("PersonId")
                        .HasColumnType("integer")
                        .HasColumnName("person_id");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at")
                        .HasDefaultValueSql("now()");

                    b.HasKey("Id")
                        .HasName("pk_attendance_response");

                    b.HasIndex("PersonId")
                        .HasDatabaseName("ix_attendance_response_person_id");

                    b.HasIndex("CalendarEntryId", "PersonId")
                        .IsUnique()
                        .HasDatabaseName("ix_attendance_response_calendar_entry_id_person_id");

                    b.ToTable("attendance_response", null, t =>
                        {
                            t.HasCheckConstraint("ck_attendance_response_answer", "answer IN ('Yes', 'No', 'Maybe')");
                        });
                });

            modelBuilder.Entity("Furria.Core.Club.BoardOffice", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateOnly?>("ArchivedOn")
                        .HasColumnType("date")
                        .HasColumnName("archived_on");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<int?>("ImpliedRoleId")
                        .HasColumnType("integer")
                        .HasColumnName("implied_role_id");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)")
                        .HasColumnName("name")
                        .UseCollation("de-DE-x-icu");

                    b.Property<int>("SortOrder")
                        .HasColumnType("integer")
                        .HasColumnName("sort_order");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at")
                        .HasDefaultValueSql("now()");

                    b.HasKey("Id")
                        .HasName("pk_board_office");

                    b.HasIndex("ImpliedRoleId")
                        .HasDatabaseName("ix_board_office_implied_role_id");

                    b.HasIndex("Name")
                        .IsUnique()
                        .HasDatabaseName("ix_board_office_name");

                    b.ToTable("board_office", (string)null);
                });

            modelBuilder.Entity("Furria.Core.Club.BoardSeat", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("BoardOfficeId")
                        .HasColumnType("integer")
                        .HasColumnName("board_office_id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<int>("PersonId")
                        .HasColumnType("integer")
                        .HasColumnName("person_id");

                    b.Property<DateOnly>("SinceOn")
                        .HasColumnType("date")
                        .HasColumnName("since_on");

                    b.Property<DateOnly?>("UntilOn")
                        .HasColumnType("date")
                        .HasColumnName("until_on");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at")
                        .HasDefaultValueSql("now()");

                    b.HasKey("Id")
                        .HasName("pk_board_seat");

                    b.HasIndex("BoardOfficeId")
                        .HasDatabaseName("ix_board_seat_board_office_id");

                    b.HasIndex("PersonId")
                        .HasDatabaseName("ix_board_seat_person_id");

                    b.ToTable("board_seat", null, t =>
                        {
                            t.HasCheckConstraint("ck_board_seat_period", "until_on IS NULL OR until_on >= since_on");
                        });
                });

            modelBuilder.Entity("Furria.Core.Club.CalendarEntry", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<bool>("AsksForResponse")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("asks_for_response");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<string>("Description")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)")
                        .HasColumnName("description");

                    b.Property<DateTimeOffset?>("EndsAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("ends_at");

                    b.Property<string>("Kind")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("kind");

                    b.Property<int?>("OwnerGroupId")
                        .HasColumnType("integer")
                        .HasColumnName("owner_group_id");

                    b.Property<DateTimeOffset>("StartsAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("starts_at");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)")
                        .HasColumnName("title");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at")
                        .HasDefaultValueSql("now()");

                    b.Property<int?>("VenueId")
                        .HasColumnType("integer")
                        .HasColumnName("venue_id");

                    b.Property<string>("Visibility")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasDefaultValue("Club")
                        .HasColumnName("visibility");

                    b.HasKey("Id")
                        .HasName("pk_calendar_entry");

                    b.HasIndex("OwnerGroupId")
                        .HasDatabaseName("ix_calendar_entry_owner_group_id");

                    b.HasIndex("StartsAt")
                        .HasDatabaseName("ix_calendar_entry_starts_at");

                    b.HasIndex("VenueId", "StartsAt")
                        .HasDatabaseName("ix_calendar_entry_venue_id_starts_at");

                    b.ToTable("calendar_entry", null, t =>
                        {
                            t.HasCheckConstraint("ck_calendar_entry_kind", "kind IN ('Training', 'Rehearsal', 'Performance', 'Meeting', 'Party', 'Other')");

                            t.HasCheckConstraint("ck_calendar_entry_owner_visibility", "owner_group_id IS NOT NULL OR visibility <> 'Group'");

                            t.HasCheckConstraint("ck_calendar_entry_visibility", "visibility IN ('Group', 'Club', 'Public')");

                            t.HasCheckConstraint("ck_calendar_entry_window", "ends_at IS NULL OR ends_at >= starts_at");
                        });
                });

            modelBuilder.Entity("Furria.Core.Club.CalendarEntryGroup", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("CalendarEntryId")
                        .HasColumnType("integer")
                        .HasColumnName("calendar_entry_id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<int>("GroupId")
                        .HasColumnType("integer")
                        .HasColumnName("group_id");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at")
                        .HasDefaultValueSql("now()");

                    b.HasKey("Id")
                        .HasName("pk_calendar_entry_group");

                    b.HasIndex("GroupId")
                        .HasDatabaseName("ix_calendar_entry_group_group_id");

                    b.HasIndex("CalendarEntryId", "GroupId")
                        .IsUnique()
                        .HasDatabaseName("ix_calendar_entry_group_calendar_entry_id_group_id");

                    b.ToTable("calendar_entry_group", (string)null);
                });

            modelBuilder.Entity("Furria.Core.Club.ClubRecord", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    b.Property<int>("AgeOfConsent")
                        .HasColumnType("integer")
                        .HasColumnName("age_of_consent");

                    b.Property<string>("City")
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)")
                        .HasColumnName("city");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("email");

                    b.Property<string>("FacebookUrl")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("facebook_url");

                    b.Property<int?>("FoundedYear")
                        .HasColumnType("integer")
                        .HasColumnName("founded_year");

                    b.Property<string>("InstagramUrl")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("instagram_url");

                    b.Property<string>("Name")
                        .HasMaxLength(160)
                        .HasColumnType("character varying(160)")
                        .HasColumnName("name");

                    b.Property<string>("Phone")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("phone");

                    b.Property<string>("ShortName")
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)")
                        .HasColumnName("short_name");

                    b.Property<string>("Street")
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)")
                        .HasColumnName("street");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at")
                        .HasDefaultValueSql("now()");

                    b.Property<string>("WebsiteUrl")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("website_url");

                    b.Property<string>("Zip")
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)")
                        .HasColumnName("zip");

                    b.HasKey("Id")
                        .HasName("pk_club_record");

                    b.ToTable("club_record", null, t =>
                        {
                            t.HasCheckConstraint("ck_club_record_age_of_consent", "age_of_consent BETWEEN 12 AND 21");

                            t.HasCheckConstraint("ck_club_record_founded_year", "founded_year IS NULL OR founded_year >= 1800");

                            t.HasCheckConstraint("ck_club_record_single", "id = 1");
                        });
                });

            modelBuilder.Entity("Furria.Core.Club.KeyHolding", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTimeOffset>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<int>("PersonId")
                        .HasColumnType("integer")
                        .HasColumnName("person_id");

                    b.Property<DateOnly>("SinceOn")
                        .HasColumnType("date")
                        .HasColumnName("since_on");

                    b.Property<DateOnly?>("UntilOn")
                        .HasColumnType("date")
                        .HasColumnName("until_on");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at")
                        .HasDefaultValueSql("now()");

                    b.Property<int>("VenueId")
                        .HasColumnType("integer")
                        .HasColumnName("venue_id");

                    b.HasKey("Id")
                        .HasName("pk_key_holding");

                    b.HasIndex("PersonId")
                        .HasDatabaseName("ix_key_holding_person_id");

                    b.HasIndex("VenueId")
                        .HasDatabaseName("ix_key_holding_venue_id");

                    b.ToTable("key_holding", null, t =>
                        {
                            t.HasCheckConstraint("ck_key_holding_period", "until_on IS NULL OR until_on >= since_on");
                        });
                });

            modelBuilder.Entity("Furria.Core.Club.Session", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTimeOffset>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<string>("LogoSvg")
                        .HasMaxLength(200000)
                        .HasColumnType("character varying(200000)")
                        .HasColumnName("logo_svg");

                    b.Property<string>("Motto")
                        .HasMaxLength(160)
                        .HasColumnType("character varying(160)")
                        .HasColumnName("motto");

                    b.Property<int?>("Number")
                        .HasColumnType("integer")
                        .HasColumnName("number");

                    b.Property<int>("StartYear")
                        .HasColumnType("integer")
                        .HasColumnName("start_year");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at")
                        .HasDefaultValueSql("now()");

                    b.HasKey("Id")
                        .HasName("pk_session");

                    b.HasIndex("Number")
                        .IsUnique()
                        .HasDatabaseName("ix_session_number")
                        .HasFilter("number IS NOT NULL");

                    b.HasIndex("StartYear")
                        .IsUnique()
                        .HasDatabaseName("ix_session_start_year");

                    b.ToTable("session", null, t =>
                        {
                            t.HasCheckConstraint("ck_session_number", "number IS NULL OR number > 0");
                        });
                });

            modelBuilder.Entity("Furria.Core.Club.Venue", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateOnly?>("ArchivedOn")
                        .HasColumnType("date")
                        .HasColumnName("archived_on");

                    b.Property<string>("City")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)")
                        .HasColumnName("city")
                        .UseCollation("de-DE-x-icu");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<string>("Hint")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("hint");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)")
                        .HasColumnName("name")
                        .UseCollation("de-DE-x-icu");

                    b.Property<int>("SortOrder")
                        .HasColumnType("integer")
                        .HasColumnName("sort_order");

                    b.Property<string>("Street")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)")
                        .HasColumnName("street");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at")
                        .HasDefaultValueSql("now()");

                    b.Property<string>("Zip")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)")
                        .HasColumnName("zip");

                    b.HasKey("Id")
                        .HasName("pk_venue");

                    b.HasIndex("Name")
                        .IsUnique()
                        .HasDatabaseName("ix_venue_name");

                    b.ToTable("venue", (string)null);
                });

            modelBuilder.Entity("Furria.Core.Groups.Group", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateOnly?>("ArchivedOn")
                        .HasColumnType("date")
                        .HasColumnName("archived_on");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(400)
                        .HasColumnType("character varying(400)")
                        .HasColumnName("description");

                    b.Property<int?>("FoundedYear")
                        .HasColumnType("integer")
                        .HasColumnName("founded_year");

                    b.Property<int?>("GroupKindId")
                        .HasColumnType("integer")
                        .HasColumnName("group_kind_id");

                    b.Property<bool>("IsRecruiting")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("is_recruiting");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)")
                        .HasColumnName("name")
                        .UseCollation("de-DE-x-icu");

                    b.Property<string>("Tone")
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("tone");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at")
                        .HasDefaultValueSql("now()");

                    b.HasKey("Id")
                        .HasName("pk_group");

                    b.HasIndex("GroupKindId")
                        .HasDatabaseName("ix_group_group_kind_id");

                    b.HasIndex("Name")
                        .HasDatabaseName("ix_group_name_lookup");

                    b.ToTable("group", null, t =>
                        {
                            t.HasCheckConstraint("ck_group_founded_year", "founded_year IS NULL OR founded_year >= 1800");

                            t.HasCheckConstraint("ck_group_tone", "tone IS NULL OR tone IN ('Clay', 'Olive', 'Lime', 'Fern', 'Teal', 'Indigo', 'Iris', 'Violet', 'Orchid', 'Rose')");
                        });
                });

            modelBuilder.Entity("Furria.Core.Groups.GroupAdmin", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTimeOffset>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<string>("Function")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("function");

                    b.Property<int>("GroupId")
                        .HasColumnType("integer")
                        .HasColumnName("group_id");

                    b.Property<int>("PersonId")
                        .HasColumnType("integer")
                        .HasColumnName("person_id");

                    b.Property<DateOnly>("SinceOn")
                        .HasColumnType("date")
                        .HasColumnName("since_on");

                    b.Property<DateOnly?>("UntilOn")
                        .HasColumnType("date")
                        .HasColumnName("until_on");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at")
                        .HasDefaultValueSql("now()");

                    b.HasKey("Id")
                        .HasName("pk_group_admin");

                    b.HasIndex("PersonId")
                        .HasDatabaseName("ix_group_admin_person_id");

                    b.HasIndex("GroupId", "PersonId")
                        .HasDatabaseName("ix_group_admin_group_id_person_id");

                    b.HasIndex(new[] { "GroupId", "PersonId" }, "ix_group_admin_group_id_person_id_open")
                        .IsUnique()
                        .HasDatabaseName("ix_group_admin_group_id_person_id_open")
                        .HasFilter("until_on IS NULL");

                    b.ToTable("group_admin", null, t =>
                        {
                            t.HasCheckConstraint("ck_group_admin_period", "until_on IS NULL OR until_on >= since_on");
                        });
                });

            modelBuilder.Entity("Furria.Core.Groups.GroupKind", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateOnly?>("ArchivedOn")
                        .HasColumnType("date")
                        .HasColumnName("archived_on");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)")
                        .HasColumnName("name")
                        .UseCollation("de-DE-x-icu");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at")
                        .HasDefaultValueSql("now()");

                    b.HasKey("Id")
                        .HasName("pk_group_kind");

                    b.HasIndex("Name")
                        .HasDatabaseName("ix_group_kind_name_lookup");

                    b.ToTable("group_kind", (string)null);
                });

            modelBuilder.Entity("Furria.Core.Groups.GroupMembership", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTimeOffset>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<int>("GroupId")
                        .HasColumnType("integer")
                        .HasColumnName("group_id");

                    b.Property<DateOnly>("JoinedOn")
                        .HasColumnType("date")
                        .HasColumnName("joined_on");

                    b.Property<DateOnly?>("LeftOn")
                        .HasColumnType("date")
                        .HasColumnName("left_on");

                    b.Property<int>("PersonId")
                        .HasColumnType("integer")
                        .HasColumnName("person_id");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at")
                        .HasDefaultValueSql("now()");

                    b.HasKey("Id")
                        .HasName("pk_group_membership");

                    b.HasIndex("PersonId")
                        .HasDatabaseName("ix_group_membership_person_id");

                    b.HasIndex("GroupId", "PersonId")
                        .HasDatabaseName("ix_group_membership_group_id_person_id");

                    b.HasIndex(new[] { "GroupId", "PersonId" }, "ix_group_membership_group_id_person_id_open")
                        .IsUnique()
                        .HasDatabaseName("ix_group_membership_group_id_person_id_open")
                        .HasFilter("left_on IS NULL");

                    b.ToTable("group_membership", null, t =>
                        {
                            t.HasCheckConstraint("ck_group_membership_period", "left_on IS NULL OR left_on >= joined_on");
                        });
                });

            modelBuilder.Entity("Furria.Core.Groups.GroupTrainingSlot", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTimeOffset>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<int>("DurationMinutes")
                        .HasColumnType("integer")
                        .HasColumnName("duration_minutes");

                    b.Property<int>("GroupId")
                        .HasColumnType("integer")
                        .HasColumnName("group_id");

                    b.Property<TimeOnly>("StartsAt")
                        .HasColumnType("time without time zone")
                        .HasColumnName("starts_at");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at")
                        .HasDefaultValueSql("now()");

                    b.Property<int?>("VenueId")
                        .HasColumnType("integer")
                        .HasColumnName("venue_id");

                    b.Property<string>("Weekday")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("weekday");

                    b.HasKey("Id")
                        .HasName("pk_group_training_slot");

                    b.HasIndex("GroupId")
                        .HasDatabaseName("ix_group_training_slot_group_id");

                    b.HasIndex("VenueId")
                        .HasDatabaseName("ix_group_training_slot_venue_id");

                    b.ToTable("group_training_slot", null, t =>
                        {
                            t.HasCheckConstraint("ck_group_training_slot_duration", "duration_minutes > 0 AND duration_minutes <= 480");

                            t.HasCheckConstraint("ck_group_training_slot_weekday", "weekday IN ('Sunday', 'Monday', 'Tuesday', 'Wednesday', 'Thursday', 'Friday', 'Saturday')");
                        });
                });

            modelBuilder.Entity("Furria.Core.Identity.FeeReduction", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Basis")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("basis");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<int>("FirstSessionYear")
                        .HasColumnType("integer")
                        .HasColumnName("first_session_year");

                    b.Property<int>("LastSessionYear")
                        .HasColumnType("integer")
                        .HasColumnName("last_session_year");

                    b.Property<int>("PersonId")
                        .HasColumnType("integer")
                        .HasColumnName("person_id");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at")
                        .HasDefaultValueSql("now()");

                    b.HasKey("Id")
                        .HasName("pk_fee_reduction");

                    b.HasIndex("PersonId")
                        .HasDatabaseName("ix_fee_reduction_person_id");

                    b.ToTable("fee_reduction", null, t =>
                        {
                            t.HasCheckConstraint("ck_fee_reduction_basis", "basis IN ('Minor', 'School', 'Apprenticeship', 'Studies')");

                            t.HasCheckConstraint("ck_fee_reduction_founding", "first_session_year >= 1971");

                            t.HasCheckConstraint("ck_fee_reduction_span", "last_session_year >= first_session_year");
                        });
                });

            modelBuilder.Entity("Furria.Core.Identity.Membership", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTimeOffset>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<DateOnly?>("EndedOn")
                        .HasColumnType("date")
                        .HasColumnName("ended_on");

                    b.Property<int>("PersonId")
                        .HasColumnType("integer")
                        .HasColumnName("person_id");

                    b.Property<DateOnly>("StartedOn")
                        .HasColumnType("date")
                        .HasColumnName("started_on");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at")
                        .HasDefaultValueSql("now()");

                    b.HasKey("Id")
                        .HasName("pk_membership");

                    b.HasIndex("PersonId")
                        .HasDatabaseName("ix_membership_person_id");

                    b.HasIndex(new[] { "PersonId" }, "ix_membership_person_id_open")
                        .IsUnique()
                        .HasDatabaseName("ix_membership_person_id_open")
                        .HasFilter("ended_on IS NULL");

                    b.ToTable("membership", null, t =>
                        {
                            t.HasCheckConstraint("ck_membership_period", "ended_on IS NULL OR ended_on >= started_on");
                        });
                });

            modelBuilder.Entity("Furria.Core.Identity.MembershipPause", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTimeOffset>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<int>("FirstSessionYear")
                        .HasColumnType("integer")
                        .HasColumnName("first_session_year");

                    b.Property<int?>("LastSessionYear")
                        .HasColumnType("integer")
                        .HasColumnName("last_session_year");

                    b.Property<int>("MembershipId")
                        .HasColumnType("integer")
                        .HasColumnName("membership_id");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at")
                        .HasDefaultValueSql("now()");

                    b.HasKey("Id")
                        .HasName("pk_membership_pause");

                    b.HasIndex("MembershipId")
                        .HasDatabaseName("ix_membership_pause_membership_id");

                    b.ToTable("membership_pause", null, t =>
                        {
                            t.HasCheckConstraint("ck_membership_pause_founding", "first_session_year >= 1971");

                            t.HasCheckConstraint("ck_membership_pause_span", "last_session_year IS NULL OR last_session_year >= first_session_year");
                        });
                });

            modelBuilder.Entity("Furria.Core.Identity.Person", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateOnly?>("BirthDate")
                        .HasColumnType("date")
                        .HasColumnName("birth_date");

                    b.Property<string>("City")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("city");

                    b.Property<bool>("ContactVisibleToMembers")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("contact_visible_to_members");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("email");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("first_name")
                        .UseCollation("de-DE-x-icu");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("last_name")
                        .UseCollation("de-DE-x-icu");

                    b.Property<string>("Phone")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("phone");

                    b.Property<bool>("PortraitIsPublic")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("portrait_is_public");

                    b.Property<string>("PortraitUrl")
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)")
                        .HasColumnName("portrait_url");

                    b.Property<string>("Street")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("street");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at")
                        .HasDefaultValueSql("now()");

                    b.Property<string>("Zip")
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)")
                        .HasColumnName("zip");

                    b.HasKey("Id")
                        .HasName("pk_person");

                    b.HasIndex("LastName", "FirstName")
                        .HasDatabaseName("ix_person_last_name_first_name");

                    b.ToTable("person", (string)null);
                });

            modelBuilder.Entity("Furria.Core.Roles.Role", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateOnly?>("ArchivedOn")
                        .HasColumnType("date")
                        .HasColumnName("archived_on");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(400)
                        .HasColumnType("character varying(400)")
                        .HasColumnName("description");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)")
                        .HasColumnName("name")
                        .UseCollation("de-DE-x-icu");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at")
                        .HasDefaultValueSql("now()");

                    b.HasKey("Id")
                        .HasName("pk_role");

                    b.HasIndex("Name")
                        .HasDatabaseName("ix_role_name_lookup");

                    b.ToTable("role", (string)null);
                });

            modelBuilder.Entity("Furria.Core.Roles.RoleHolding", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTimeOffset>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<int>("PersonId")
                        .HasColumnType("integer")
                        .HasColumnName("person_id");

                    b.Property<int>("RoleId")
                        .HasColumnType("integer")
                        .HasColumnName("role_id");

                    b.Property<DateOnly>("SinceOn")
                        .HasColumnType("date")
                        .HasColumnName("since_on");

                    b.Property<DateOnly?>("UntilOn")
                        .HasColumnType("date")
                        .HasColumnName("until_on");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at")
                        .HasDefaultValueSql("now()");

                    b.HasKey("Id")
                        .HasName("pk_role_holding");

                    b.HasIndex("PersonId")
                        .HasDatabaseName("ix_role_holding_person_id");

                    b.HasIndex("RoleId", "PersonId")
                        .HasDatabaseName("ix_role_holding_role_id_person_id");

                    b.HasIndex(new[] { "RoleId", "PersonId" }, "ix_role_holding_role_id_person_id_open")
                        .IsUnique()
                        .HasDatabaseName("ix_role_holding_role_id_person_id_open")
                        .HasFilter("until_on IS NULL");

                    b.ToTable("role_holding", null, t =>
                        {
                            t.HasCheckConstraint("ck_role_holding_period", "until_on IS NULL OR until_on >= since_on");
                        });
                });

            modelBuilder.Entity("Furria.Core.Roles.RolePermission", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTimeOffset>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<string>("PermissionKey")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("permission_key");

                    b.Property<int>("RoleId")
                        .HasColumnType("integer")
                        .HasColumnName("role_id");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at")
                        .HasDefaultValueSql("now()");

                    b.HasKey("Id")
                        .HasName("pk_role_permission");

                    b.HasIndex("RoleId", "PermissionKey")
                        .IsUnique()
                        .HasDatabaseName("ix_role_permission_role_id_permission_key");

                    b.ToTable("role_permission", (string)null);
                });

            modelBuilder.Entity("Furria.Infrastructure.Identity.Account", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("integer")
                        .HasColumnName("access_failed_count");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("text")
                        .HasColumnName("concurrency_stamp");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("email");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("boolean")
                        .HasColumnName("email_confirmed");

                    b.Property<bool>("IsDisabled")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("is_disabled");

                    b.Property<DateTimeOffset?>("LastSeenAnnouncementAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_seen_announcement_at");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("boolean")
                        .HasColumnName("lockout_enabled");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("lockout_end");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("normalized_email");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("normalized_user_name");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("text")
                        .HasColumnName("password_hash");

                    b.Property<int>("PersonId")
                        .HasColumnType("integer")
                        .HasColumnName("person_id");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("text")
                        .HasColumnName("phone_number");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("boolean")
                        .HasColumnName("phone_number_confirmed");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("text")
                        .HasColumnName("security_stamp");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("boolean")
                        .HasColumnName("two_factor_enabled");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("user_name");

                    b.HasKey("Id")
                        .HasName("pk_account");

                    b.HasIndex("NormalizedEmail")
                        .IsUnique()
                        .HasDatabaseName("ix_account_normalized_email");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("ix_account_normalized_user_name");

                    b.HasIndex("PersonId")
                        .IsUnique()
                        .HasDatabaseName("ix_account_person_id");

                    b.ToTable("account", (string)null);
                });

            modelBuilder.Entity("Furria.Infrastructure.Identity.RefreshToken", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<int>("AccountId")
                        .HasColumnType("integer")
                        .HasColumnName("account_id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<DateTimeOffset>("ExpiresAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("expires_at");

                    b.Property<Guid>("FamilyId")
                        .HasColumnType("uuid")
                        .HasColumnName("family_id");

                    b.Property<Guid?>("ReplacedById")
                        .HasColumnType("uuid")
                        .HasColumnName("replaced_by_id");

                    b.Property<DateTimeOffset?>("RevokedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("revoked_at");

                    b.Property<string>("RevokedReason")
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("revoked_reason");

                    b.Property<string>("TokenHash")
                        .IsRequired()
                        .HasMaxLength(43)
                        .HasColumnType("character varying(43)")
                        .HasColumnName("token_hash");

                    b.HasKey("Id")
                        .HasName("pk_refresh_token");

                    b.HasIndex("AccountId")
                        .HasDatabaseName("ix_refresh_token_account_id");

                    b.HasIndex("ExpiresAt")
                        .HasDatabaseName("ix_refresh_token_expires_at");

                    b.HasIndex("FamilyId")
                        .HasDatabaseName("ix_refresh_token_family_id");

                    b.HasIndex("ReplacedById")
                        .IsUnique()
                        .HasDatabaseName("ix_refresh_token_replaced_by_id");

                    b.HasIndex("TokenHash")
                        .IsUnique()
                        .HasDatabaseName("ix_refresh_token_token_hash");

                    b.ToTable("refresh_token", null, t =>
                        {
                            t.HasCheckConstraint("ck_refresh_token_expiry", "expires_at > created_at");

                            t.HasCheckConstraint("ck_refresh_token_revocation", "(revoked_at IS NULL) = (revoked_reason IS NULL)");
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<int>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("text")
                        .HasColumnName("claim_type");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("text")
                        .HasColumnName("claim_value");

                    b.Property<int>("UserId")
                        .HasColumnType("integer")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("pk_account_claim");

                    b.HasIndex("UserId")
                        .HasDatabaseName("ix_account_claim_user_id");

                    b.ToTable("account_claim", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<int>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("text")
                        .HasColumnName("login_provider");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("text")
                        .HasColumnName("provider_key");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("text")
                        .HasColumnName("provider_display_name");

                    b.Property<int>("UserId")
                        .HasColumnType("integer")
                        .HasColumnName("user_id");

                    b.HasKey("LoginProvider", "ProviderKey")
                        .HasName("pk_account_login");

                    b.HasIndex("UserId")
                        .HasDatabaseName("ix_account_login_user_id");

                    b.ToTable("account_login", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<int>", b =>
                {
                    b.Property<int>("UserId")
                        .HasColumnType("integer")
                        .HasColumnName("user_id");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("text")
                        .HasColumnName("login_provider");

                    b.Property<string>("Name")
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<string>("Value")
                        .HasColumnType("text")
                        .HasColumnName("value");

                    b.HasKey("UserId", "LoginProvider", "Name")
                        .HasName("pk_account_token");

                    b.ToTable("account_token", (string)null);
                });

            modelBuilder.Entity("Furria.Core.Club.Announcement", b =>
                {
                    b.HasOne("Furria.Core.Identity.Person", "Author")
                        .WithMany()
                        .HasForeignKey("AuthorPersonId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_announcement_person_author_person_id");

                    b.Navigation("Author");
                });

            modelBuilder.Entity("Furria.Core.Club.AttendanceResponse", b =>
                {
                    b.HasOne("Furria.Core.Club.CalendarEntry", "CalendarEntry")
                        .WithMany()
                        .HasForeignKey("CalendarEntryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_attendance_response_calendar_entry_calendar_entry_id");

                    b.HasOne("Furria.Core.Identity.Person", "Person")
                        .WithMany()
                        .HasForeignKey("PersonId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_attendance_response_person_person_id");

                    b.Navigation("CalendarEntry");

                    b.Navigation("Person");
                });

            modelBuilder.Entity("Furria.Core.Club.BoardOffice", b =>
                {
                    b.HasOne("Furria.Core.Roles.Role", "ImpliedRole")
                        .WithMany()
                        .HasForeignKey("ImpliedRoleId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("fk_board_office_role_implied_role_id");

                    b.Navigation("ImpliedRole");
                });

            modelBuilder.Entity("Furria.Core.Club.BoardSeat", b =>
                {
                    b.HasOne("Furria.Core.Club.BoardOffice", "BoardOffice")
                        .WithMany()
                        .HasForeignKey("BoardOfficeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_board_seat_board_office_board_office_id");

                    b.HasOne("Furria.Core.Identity.Person", "Person")
                        .WithMany()
                        .HasForeignKey("PersonId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_board_seat_person_person_id");

                    b.Navigation("BoardOffice");

                    b.Navigation("Person");
                });

            modelBuilder.Entity("Furria.Core.Club.CalendarEntry", b =>
                {
                    b.HasOne("Furria.Core.Groups.Group", "OwnerGroup")
                        .WithMany()
                        .HasForeignKey("OwnerGroupId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("fk_calendar_entry_group_owner_group_id");

                    b.HasOne("Furria.Core.Club.Venue", "Venue")
                        .WithMany()
                        .HasForeignKey("VenueId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("fk_calendar_entry_venue_venue_id");

                    b.Navigation("OwnerGroup");

                    b.Navigation("Venue");
                });

            modelBuilder.Entity("Furria.Core.Club.CalendarEntryGroup", b =>
                {
                    b.HasOne("Furria.Core.Club.CalendarEntry", "CalendarEntry")
                        .WithMany("ParticipatingGroups")
                        .HasForeignKey("CalendarEntryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_calendar_entry_group_calendar_entry_calendar_entry_id");

                    b.HasOne("Furria.Core.Groups.Group", "Group")
                        .WithMany()
                        .HasForeignKey("GroupId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_calendar_entry_group_group_group_id");

                    b.Navigation("CalendarEntry");

                    b.Navigation("Group");
                });

            modelBuilder.Entity("Furria.Core.Club.KeyHolding", b =>
                {
                    b.HasOne("Furria.Core.Identity.Person", "Person")
                        .WithMany()
                        .HasForeignKey("PersonId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_key_holding_person_person_id");

                    b.HasOne("Furria.Core.Club.Venue", "Venue")
                        .WithMany()
                        .HasForeignKey("VenueId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_key_holding_venue_venue_id");

                    b.Navigation("Person");

                    b.Navigation("Venue");
                });

            modelBuilder.Entity("Furria.Core.Groups.Group", b =>
                {
                    b.HasOne("Furria.Core.Groups.GroupKind", "GroupKind")
                        .WithMany()
                        .HasForeignKey("GroupKindId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("fk_group_group_kind_group_kind_id");

                    b.Navigation("GroupKind");
                });

            modelBuilder.Entity("Furria.Core.Groups.GroupAdmin", b =>
                {
                    b.HasOne("Furria.Core.Groups.Group", "Group")
                        .WithMany("Admins")
                        .HasForeignKey("GroupId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_group_admin_group_group_id");

                    b.HasOne("Furria.Core.Identity.Person", "Person")
                        .WithMany("GroupAdminships")
                        .HasForeignKey("PersonId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_group_admin_person_person_id");

                    b.Navigation("Group");

                    b.Navigation("Person");
                });

            modelBuilder.Entity("Furria.Core.Groups.GroupMembership", b =>
                {
                    b.HasOne("Furria.Core.Groups.Group", "Group")
                        .WithMany("Memberships")
                        .HasForeignKey("GroupId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_group_membership_group_group_id");

                    b.HasOne("Furria.Core.Identity.Person", "Person")
                        .WithMany("GroupMemberships")
                        .HasForeignKey("PersonId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_group_membership_person_person_id");

                    b.Navigation("Group");

                    b.Navigation("Person");
                });

            modelBuilder.Entity("Furria.Core.Groups.GroupTrainingSlot", b =>
                {
                    b.HasOne("Furria.Core.Groups.Group", "Group")
                        .WithMany("TrainingSlots")
                        .HasForeignKey("GroupId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_group_training_slot_group_group_id");

                    b.HasOne("Furria.Core.Club.Venue", "Venue")
                        .WithMany()
                        .HasForeignKey("VenueId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("fk_group_training_slot_venue_venue_id");

                    b.Navigation("Group");

                    b.Navigation("Venue");
                });

            modelBuilder.Entity("Furria.Core.Identity.FeeReduction", b =>
                {
                    b.HasOne("Furria.Core.Identity.Person", "Person")
                        .WithMany("FeeReductions")
                        .HasForeignKey("PersonId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_fee_reduction_person_person_id");

                    b.Navigation("Person");
                });

            modelBuilder.Entity("Furria.Core.Identity.Membership", b =>
                {
                    b.HasOne("Furria.Core.Identity.Person", "Person")
                        .WithMany("Memberships")
                        .HasForeignKey("PersonId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_membership_person_person_id");

                    b.Navigation("Person");
                });

            modelBuilder.Entity("Furria.Core.Identity.MembershipPause", b =>
                {
                    b.HasOne("Furria.Core.Identity.Membership", "Membership")
                        .WithMany("Pauses")
                        .HasForeignKey("MembershipId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_membership_pause_membership_membership_id");

                    b.Navigation("Membership");
                });

            modelBuilder.Entity("Furria.Core.Roles.RoleHolding", b =>
                {
                    b.HasOne("Furria.Core.Identity.Person", "Person")
                        .WithMany("RoleHoldings")
                        .HasForeignKey("PersonId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_role_holding_person_person_id");

                    b.HasOne("Furria.Core.Roles.Role", "Role")
                        .WithMany("Holdings")
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_role_holding_role_role_id");

                    b.Navigation("Person");

                    b.Navigation("Role");
                });

            modelBuilder.Entity("Furria.Core.Roles.RolePermission", b =>
                {
                    b.HasOne("Furria.Core.Roles.Role", "Role")
                        .WithMany("Permissions")
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_role_permission_role_role_id");

                    b.Navigation("Role");
                });

            modelBuilder.Entity("Furria.Infrastructure.Identity.Account", b =>
                {
                    b.HasOne("Furria.Core.Identity.Person", "Person")
                        .WithOne()
                        .HasForeignKey("Furria.Infrastructure.Identity.Account", "PersonId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_account_person_person_id");

                    b.Navigation("Person");
                });

            modelBuilder.Entity("Furria.Infrastructure.Identity.RefreshToken", b =>
                {
                    b.HasOne("Furria.Infrastructure.Identity.Account", "Account")
                        .WithMany()
                        .HasForeignKey("AccountId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_refresh_token_account_account_id");

                    b.Navigation("Account");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<int>", b =>
                {
                    b.HasOne("Furria.Infrastructure.Identity.Account", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_account_claim_account_user_id");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<int>", b =>
                {
                    b.HasOne("Furria.Infrastructure.Identity.Account", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_account_login_account_user_id");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<int>", b =>
                {
                    b.HasOne("Furria.Infrastructure.Identity.Account", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_account_token_account_user_id");
                });

            modelBuilder.Entity("Furria.Core.Club.CalendarEntry", b =>
                {
                    b.Navigation("ParticipatingGroups");
                });

            modelBuilder.Entity("Furria.Core.Groups.Group", b =>
                {
                    b.Navigation("Admins");

                    b.Navigation("Memberships");

                    b.Navigation("TrainingSlots");
                });

            modelBuilder.Entity("Furria.Core.Identity.Membership", b =>
                {
                    b.Navigation("Pauses");
                });

            modelBuilder.Entity("Furria.Core.Identity.Person", b =>
                {
                    b.Navigation("FeeReductions");

                    b.Navigation("GroupAdminships");

                    b.Navigation("GroupMemberships");

                    b.Navigation("Memberships");

                    b.Navigation("RoleHoldings");
                });

            modelBuilder.Entity("Furria.Core.Roles.Role", b =>
                {
                    b.Navigation("Holdings");

                    b.Navigation("Permissions");
                });
#pragma warning restore 612, 618
        }
    }
}
