// <auto-generated />
using System;
using Furria.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Furria.Infrastructure.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260911134344_FeeReductionBasis")]
    partial class FeeReductionBasis
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Furria.Core.Groups.Group", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateOnly?>("ArchivedOn")
                        .HasColumnType("date")
                        .HasColumnName("archived_on");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(400)
                        .HasColumnType("character varying(400)")
                        .HasColumnName("description");

                    b.Property<bool>("IsRecruiting")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("is_recruiting");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)")
                        .HasColumnName("name")
                        .UseCollation("de-DE-x-icu");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at")
                        .HasDefaultValueSql("now()");

                    b.HasKey("Id")
                        .HasName("pk_group");

                    b.HasIndex("Name")
                        .HasDatabaseName("ix_group_name_lookup");

                    b.ToTable("group", (string)null);
                });

            modelBuilder.Entity("Furria.Core.Groups.GroupAdmin", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTimeOffset>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<string>("Function")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("function");

                    b.Property<int>("GroupId")
                        .HasColumnType("integer")
                        .HasColumnName("group_id");

                    b.Property<int>("PersonId")
                        .HasColumnType("integer")
                        .HasColumnName("person_id");

                    b.Property<DateOnly>("SinceOn")
                        .HasColumnType("date")
                        .HasColumnName("since_on");

                    b.Property<DateOnly?>("UntilOn")
                        .HasColumnType("date")
                        .HasColumnName("until_on");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at")
                        .HasDefaultValueSql("now()");

                    b.HasKey("Id")
                        .HasName("pk_group_admin");

                    b.HasIndex("PersonId")
                        .HasDatabaseName("ix_group_admin_person_id");

                    b.HasIndex("GroupId", "PersonId")
                        .HasDatabaseName("ix_group_admin_group_id_person_id");

                    b.HasIndex(new[] { "GroupId", "PersonId" }, "ix_group_admin_group_id_person_id_open")
                        .IsUnique()
                        .HasDatabaseName("ix_group_admin_group_id_person_id_open")
                        .HasFilter("until_on IS NULL");

                    b.ToTable("group_admin", null, t =>
                        {
                            t.HasCheckConstraint("ck_group_admin_period", "until_on IS NULL OR until_on >= since_on");
                        });
                });

            modelBuilder.Entity("Furria.Core.Groups.GroupMembership", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTimeOffset>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<int>("GroupId")
                        .HasColumnType("integer")
                        .HasColumnName("group_id");

                    b.Property<DateOnly>("JoinedOn")
                        .HasColumnType("date")
                        .HasColumnName("joined_on");

                    b.Property<DateOnly?>("LeftOn")
                        .HasColumnType("date")
                        .HasColumnName("left_on");

                    b.Property<int>("PersonId")
                        .HasColumnType("integer")
                        .HasColumnName("person_id");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at")
                        .HasDefaultValueSql("now()");

                    b.HasKey("Id")
                        .HasName("pk_group_membership");

                    b.HasIndex("PersonId")
                        .HasDatabaseName("ix_group_membership_person_id");

                    b.HasIndex("GroupId", "PersonId")
                        .HasDatabaseName("ix_group_membership_group_id_person_id");

                    b.HasIndex(new[] { "GroupId", "PersonId" }, "ix_group_membership_group_id_person_id_open")
                        .IsUnique()
                        .HasDatabaseName("ix_group_membership_group_id_person_id_open")
                        .HasFilter("left_on IS NULL");

                    b.ToTable("group_membership", null, t =>
                        {
                            t.HasCheckConstraint("ck_group_membership_period", "left_on IS NULL OR left_on >= joined_on");
                        });
                });

            modelBuilder.Entity("Furria.Core.Identity.FeeReduction", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Basis")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("basis");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<int>("FirstSessionYear")
                        .HasColumnType("integer")
                        .HasColumnName("first_session_year");

                    b.Property<int>("LastSessionYear")
                        .HasColumnType("integer")
                        .HasColumnName("last_session_year");

                    b.Property<int>("PersonId")
                        .HasColumnType("integer")
                        .HasColumnName("person_id");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at")
                        .HasDefaultValueSql("now()");

                    b.HasKey("Id")
                        .HasName("pk_fee_reduction");

                    b.HasIndex("PersonId")
                        .HasDatabaseName("ix_fee_reduction_person_id");

                    b.ToTable("fee_reduction", null, t =>
                        {
                            t.HasCheckConstraint("ck_fee_reduction_basis", "basis IN ('Minor', 'School', 'Apprenticeship', 'Studies')");

                            t.HasCheckConstraint("ck_fee_reduction_founding", "first_session_year >= 1971");

                            t.HasCheckConstraint("ck_fee_reduction_span", "last_session_year >= first_session_year");
                        });
                });

            modelBuilder.Entity("Furria.Core.Identity.Membership", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTimeOffset>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<DateOnly?>("EndedOn")
                        .HasColumnType("date")
                        .HasColumnName("ended_on");

                    b.Property<int>("PersonId")
                        .HasColumnType("integer")
                        .HasColumnName("person_id");

                    b.Property<DateOnly>("StartedOn")
                        .HasColumnType("date")
                        .HasColumnName("started_on");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at")
                        .HasDefaultValueSql("now()");

                    b.HasKey("Id")
                        .HasName("pk_membership");

                    b.HasIndex("PersonId")
                        .HasDatabaseName("ix_membership_person_id");

                    b.HasIndex(new[] { "PersonId" }, "ix_membership_person_id_open")
                        .IsUnique()
                        .HasDatabaseName("ix_membership_person_id_open")
                        .HasFilter("ended_on IS NULL");

                    b.ToTable("membership", null, t =>
                        {
                            t.HasCheckConstraint("ck_membership_period", "ended_on IS NULL OR ended_on >= started_on");
                        });
                });

            modelBuilder.Entity("Furria.Core.Identity.MembershipPause", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTimeOffset>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<int>("FirstSessionYear")
                        .HasColumnType("integer")
                        .HasColumnName("first_session_year");

                    b.Property<int?>("LastSessionYear")
                        .HasColumnType("integer")
                        .HasColumnName("last_session_year");

                    b.Property<int>("MembershipId")
                        .HasColumnType("integer")
                        .HasColumnName("membership_id");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at")
                        .HasDefaultValueSql("now()");

                    b.HasKey("Id")
                        .HasName("pk_membership_pause");

                    b.HasIndex("MembershipId")
                        .HasDatabaseName("ix_membership_pause_membership_id");

                    b.ToTable("membership_pause", null, t =>
                        {
                            t.HasCheckConstraint("ck_membership_pause_founding", "first_session_year >= 1971");

                            t.HasCheckConstraint("ck_membership_pause_span", "last_session_year IS NULL OR last_session_year >= first_session_year");
                        });
                });

            modelBuilder.Entity("Furria.Core.Identity.Person", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateOnly?>("BirthDate")
                        .HasColumnType("date")
                        .HasColumnName("birth_date");

                    b.Property<string>("City")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("city");

                    b.Property<bool>("ContactVisibleToMembers")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("contact_visible_to_members");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("email");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("first_name")
                        .UseCollation("de-DE-x-icu");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("last_name")
                        .UseCollation("de-DE-x-icu");

                    b.Property<string>("Phone")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("phone");

                    b.Property<string>("Street")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("street");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at")
                        .HasDefaultValueSql("now()");

                    b.Property<string>("Zip")
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)")
                        .HasColumnName("zip");

                    b.HasKey("Id")
                        .HasName("pk_person");

                    b.HasIndex("LastName", "FirstName")
                        .HasDatabaseName("ix_person_last_name_first_name");

                    b.ToTable("person", (string)null);
                });

            modelBuilder.Entity("Furria.Core.Roles.Role", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateOnly?>("ArchivedOn")
                        .HasColumnType("date")
                        .HasColumnName("archived_on");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(400)
                        .HasColumnType("character varying(400)")
                        .HasColumnName("description");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)")
                        .HasColumnName("name")
                        .UseCollation("de-DE-x-icu");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at")
                        .HasDefaultValueSql("now()");

                    b.HasKey("Id")
                        .HasName("pk_role");

                    b.HasIndex("Name")
                        .HasDatabaseName("ix_role_name_lookup");

                    b.ToTable("role", (string)null);
                });

            modelBuilder.Entity("Furria.Core.Roles.RoleHolding", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTimeOffset>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<int>("PersonId")
                        .HasColumnType("integer")
                        .HasColumnName("person_id");

                    b.Property<int>("RoleId")
                        .HasColumnType("integer")
                        .HasColumnName("role_id");

                    b.Property<DateOnly>("SinceOn")
                        .HasColumnType("date")
                        .HasColumnName("since_on");

                    b.Property<DateOnly?>("UntilOn")
                        .HasColumnType("date")
                        .HasColumnName("until_on");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at")
                        .HasDefaultValueSql("now()");

                    b.HasKey("Id")
                        .HasName("pk_role_holding");

                    b.HasIndex("PersonId")
                        .HasDatabaseName("ix_role_holding_person_id");

                    b.HasIndex("RoleId", "PersonId")
                        .HasDatabaseName("ix_role_holding_role_id_person_id");

                    b.HasIndex(new[] { "RoleId", "PersonId" }, "ix_role_holding_role_id_person_id_open")
                        .IsUnique()
                        .HasDatabaseName("ix_role_holding_role_id_person_id_open")
                        .HasFilter("until_on IS NULL");

                    b.ToTable("role_holding", null, t =>
                        {
                            t.HasCheckConstraint("ck_role_holding_period", "until_on IS NULL OR until_on >= since_on");
                        });
                });

            modelBuilder.Entity("Furria.Core.Roles.RolePermission", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTimeOffset>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<string>("PermissionKey")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("permission_key");

                    b.Property<int>("RoleId")
                        .HasColumnType("integer")
                        .HasColumnName("role_id");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at")
                        .HasDefaultValueSql("now()");

                    b.HasKey("Id")
                        .HasName("pk_role_permission");

                    b.HasIndex("RoleId", "PermissionKey")
                        .IsUnique()
                        .HasDatabaseName("ix_role_permission_role_id_permission_key");

                    b.ToTable("role_permission", (string)null);
                });

            modelBuilder.Entity("Furria.Infrastructure.Identity.Account", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("integer")
                        .HasColumnName("access_failed_count");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("text")
                        .HasColumnName("concurrency_stamp");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("email");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("boolean")
                        .HasColumnName("email_confirmed");

                    b.Property<bool>("IsDisabled")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("is_disabled");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("boolean")
                        .HasColumnName("lockout_enabled");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("lockout_end");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("normalized_email");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("normalized_user_name");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("text")
                        .HasColumnName("password_hash");

                    b.Property<int>("PersonId")
                        .HasColumnType("integer")
                        .HasColumnName("person_id");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("text")
                        .HasColumnName("phone_number");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("boolean")
                        .HasColumnName("phone_number_confirmed");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("text")
                        .HasColumnName("security_stamp");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("boolean")
                        .HasColumnName("two_factor_enabled");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("user_name");

                    b.HasKey("Id")
                        .HasName("pk_account");

                    b.HasIndex("NormalizedEmail")
                        .IsUnique()
                        .HasDatabaseName("ix_account_normalized_email");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("ix_account_normalized_user_name");

                    b.HasIndex("PersonId")
                        .IsUnique()
                        .HasDatabaseName("ix_account_person_id");

                    b.ToTable("account", (string)null);
                });

            modelBuilder.Entity("Furria.Infrastructure.Identity.RefreshToken", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<int>("AccountId")
                        .HasColumnType("integer")
                        .HasColumnName("account_id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<DateTimeOffset>("ExpiresAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("expires_at");

                    b.Property<Guid>("FamilyId")
                        .HasColumnType("uuid")
                        .HasColumnName("family_id");

                    b.Property<Guid?>("ReplacedById")
                        .HasColumnType("uuid")
                        .HasColumnName("replaced_by_id");

                    b.Property<DateTimeOffset?>("RevokedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("revoked_at");

                    b.Property<string>("RevokedReason")
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("revoked_reason");

                    b.Property<string>("TokenHash")
                        .IsRequired()
                        .HasMaxLength(43)
                        .HasColumnType("character varying(43)")
                        .HasColumnName("token_hash");

                    b.HasKey("Id")
                        .HasName("pk_refresh_token");

                    b.HasIndex("AccountId")
                        .HasDatabaseName("ix_refresh_token_account_id");

                    b.HasIndex("ExpiresAt")
                        .HasDatabaseName("ix_refresh_token_expires_at");

                    b.HasIndex("FamilyId")
                        .HasDatabaseName("ix_refresh_token_family_id");

                    b.HasIndex("ReplacedById")
                        .IsUnique()
                        .HasDatabaseName("ix_refresh_token_replaced_by_id");

                    b.HasIndex("TokenHash")
                        .IsUnique()
                        .HasDatabaseName("ix_refresh_token_token_hash");

                    b.ToTable("refresh_token", null, t =>
                        {
                            t.HasCheckConstraint("ck_refresh_token_expiry", "expires_at > created_at");

                            t.HasCheckConstraint("ck_refresh_token_revocation", "(revoked_at IS NULL) = (revoked_reason IS NULL)");
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<int>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("text")
                        .HasColumnName("claim_type");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("text")
                        .HasColumnName("claim_value");

                    b.Property<int>("UserId")
                        .HasColumnType("integer")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("pk_account_claim");

                    b.HasIndex("UserId")
                        .HasDatabaseName("ix_account_claim_user_id");

                    b.ToTable("account_claim", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<int>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("text")
                        .HasColumnName("login_provider");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("text")
                        .HasColumnName("provider_key");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("text")
                        .HasColumnName("provider_display_name");

                    b.Property<int>("UserId")
                        .HasColumnType("integer")
                        .HasColumnName("user_id");

                    b.HasKey("LoginProvider", "ProviderKey")
                        .HasName("pk_account_login");

                    b.HasIndex("UserId")
                        .HasDatabaseName("ix_account_login_user_id");

                    b.ToTable("account_login", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<int>", b =>
                {
                    b.Property<int>("UserId")
                        .HasColumnType("integer")
                        .HasColumnName("user_id");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("text")
                        .HasColumnName("login_provider");

                    b.Property<string>("Name")
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<string>("Value")
                        .HasColumnType("text")
                        .HasColumnName("value");

                    b.HasKey("UserId", "LoginProvider", "Name")
                        .HasName("pk_account_token");

                    b.ToTable("account_token", (string)null);
                });

            modelBuilder.Entity("Furria.Core.Groups.GroupAdmin", b =>
                {
                    b.HasOne("Furria.Core.Groups.Group", "Group")
                        .WithMany("Admins")
                        .HasForeignKey("GroupId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_group_admin_group_group_id");

                    b.HasOne("Furria.Core.Identity.Person", "Person")
                        .WithMany("GroupAdminships")
                        .HasForeignKey("PersonId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_group_admin_person_person_id");

                    b.Navigation("Group");

                    b.Navigation("Person");
                });

            modelBuilder.Entity("Furria.Core.Groups.GroupMembership", b =>
                {
                    b.HasOne("Furria.Core.Groups.Group", "Group")
                        .WithMany("Memberships")
                        .HasForeignKey("GroupId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_group_membership_group_group_id");

                    b.HasOne("Furria.Core.Identity.Person", "Person")
                        .WithMany("GroupMemberships")
                        .HasForeignKey("PersonId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_group_membership_person_person_id");

                    b.Navigation("Group");

                    b.Navigation("Person");
                });

            modelBuilder.Entity("Furria.Core.Identity.FeeReduction", b =>
                {
                    b.HasOne("Furria.Core.Identity.Person", "Person")
                        .WithMany("FeeReductions")
                        .HasForeignKey("PersonId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_fee_reduction_person_person_id");

                    b.Navigation("Person");
                });

            modelBuilder.Entity("Furria.Core.Identity.Membership", b =>
                {
                    b.HasOne("Furria.Core.Identity.Person", "Person")
                        .WithMany("Memberships")
                        .HasForeignKey("PersonId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_membership_person_person_id");

                    b.Navigation("Person");
                });

            modelBuilder.Entity("Furria.Core.Identity.MembershipPause", b =>
                {
                    b.HasOne("Furria.Core.Identity.Membership", "Membership")
                        .WithMany("Pauses")
                        .HasForeignKey("MembershipId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_membership_pause_membership_membership_id");

                    b.Navigation("Membership");
                });

            modelBuilder.Entity("Furria.Core.Roles.RoleHolding", b =>
                {
                    b.HasOne("Furria.Core.Identity.Person", "Person")
                        .WithMany("RoleHoldings")
                        .HasForeignKey("PersonId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_role_holding_person_person_id");

                    b.HasOne("Furria.Core.Roles.Role", "Role")
                        .WithMany("Holdings")
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_role_holding_role_role_id");

                    b.Navigation("Person");

                    b.Navigation("Role");
                });

            modelBuilder.Entity("Furria.Core.Roles.RolePermission", b =>
                {
                    b.HasOne("Furria.Core.Roles.Role", "Role")
                        .WithMany("Permissions")
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_role_permission_role_role_id");

                    b.Navigation("Role");
                });

            modelBuilder.Entity("Furria.Infrastructure.Identity.Account", b =>
                {
                    b.HasOne("Furria.Core.Identity.Person", "Person")
                        .WithOne()
                        .HasForeignKey("Furria.Infrastructure.Identity.Account", "PersonId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_account_person_person_id");

                    b.Navigation("Person");
                });

            modelBuilder.Entity("Furria.Infrastructure.Identity.RefreshToken", b =>
                {
                    b.HasOne("Furria.Infrastructure.Identity.Account", "Account")
                        .WithMany()
                        .HasForeignKey("AccountId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_refresh_token_account_account_id");

                    b.Navigation("Account");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<int>", b =>
                {
                    b.HasOne("Furria.Infrastructure.Identity.Account", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_account_claim_account_user_id");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<int>", b =>
                {
                    b.HasOne("Furria.Infrastructure.Identity.Account", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_account_login_account_user_id");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<int>", b =>
                {
                    b.HasOne("Furria.Infrastructure.Identity.Account", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_account_token_account_user_id");
                });

            modelBuilder.Entity("Furria.Core.Groups.Group", b =>
                {
                    b.Navigation("Admins");

                    b.Navigation("Memberships");
                });

            modelBuilder.Entity("Furria.Core.Identity.Membership", b =>
                {
                    b.Navigation("Pauses");
                });

            modelBuilder.Entity("Furria.Core.Identity.Person", b =>
                {
                    b.Navigation("FeeReductions");

                    b.Navigation("GroupAdminships");

                    b.Navigation("GroupMemberships");

                    b.Navigation("Memberships");

                    b.Navigation("RoleHoldings");
                });

            modelBuilder.Entity("Furria.Core.Roles.Role", b =>
                {
                    b.Navigation("Holdings");

                    b.Navigation("Permissions");
                });
#pragma warning restore 612, 618
        }
    }
}
