/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AppRouteImport } from './routes/_app'
import { Route as AppIndexRouteImport } from './routes/_app/index'
import { Route as AppProfileRouteImport } from './routes/_app/profile'
import { Route as AppAffiliatedRouteImport } from './routes/_app/_affiliated'
import { Route as AppMyGroupsIndexRouteImport } from './routes/_app/my-groups.index'
import { Route as AppMyGroupsGroupIdRouteImport } from './routes/_app/my-groups.$groupId'
import { Route as AppManagePersonsRouteImport } from './routes/_app/manage.persons'
import { Route as AppAffiliatedMembersRouteImport } from './routes/_app/_affiliated.members'
import { Route as AppAffiliatedGroupsRouteImport } from './routes/_app/_affiliated.groups'
import { Route as AppManagePersonsPersonIdRouteImport } from './routes/_app/manage.persons_.$personId'
import { Route as AppAffiliatedMembersPersonIdRouteImport } from './routes/_app/_affiliated.members_.$personId'
import { Route as AppAffiliatedGroupsGroupIdRouteImport } from './routes/_app/_affiliated.groups_.$groupId'

const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRoute,
} as any)
const AppProfileRoute = AppProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => AppRoute,
} as any)
const AppAffiliatedRoute = AppAffiliatedRouteImport.update({
  id: '/_affiliated',
  getParentRoute: () => AppRoute,
} as any)
const AppMyGroupsIndexRoute = AppMyGroupsIndexRouteImport.update({
  id: '/my-groups/',
  path: '/my-groups/',
  getParentRoute: () => AppRoute,
} as any)
const AppMyGroupsGroupIdRoute = AppMyGroupsGroupIdRouteImport.update({
  id: '/my-groups/$groupId',
  path: '/my-groups/$groupId',
  getParentRoute: () => AppRoute,
} as any)
const AppManagePersonsRoute = AppManagePersonsRouteImport.update({
  id: '/manage/persons',
  path: '/manage/persons',
  getParentRoute: () => AppRoute,
} as any)
const AppAffiliatedMembersRoute = AppAffiliatedMembersRouteImport.update({
  id: '/members',
  path: '/members',
  getParentRoute: () => AppAffiliatedRoute,
} as any)
const AppAffiliatedGroupsRoute = AppAffiliatedGroupsRouteImport.update({
  id: '/groups',
  path: '/groups',
  getParentRoute: () => AppAffiliatedRoute,
} as any)
const AppManagePersonsPersonIdRoute =
  AppManagePersonsPersonIdRouteImport.update({
    id: '/manage/persons_/$personId',
    path: '/manage/persons/$personId',
    getParentRoute: () => AppRoute,
  } as any)
const AppAffiliatedMembersPersonIdRoute =
  AppAffiliatedMembersPersonIdRouteImport.update({
    id: '/members_/$personId',
    path: '/members/$personId',
    getParentRoute: () => AppAffiliatedRoute,
  } as any)
const AppAffiliatedGroupsGroupIdRoute =
  AppAffiliatedGroupsGroupIdRouteImport.update({
    id: '/groups_/$groupId',
    path: '/groups/$groupId',
    getParentRoute: () => AppAffiliatedRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof AppIndexRoute
  '/login': typeof LoginRoute
  '/profile': typeof AppProfileRoute
  '/groups': typeof AppAffiliatedGroupsRoute
  '/members': typeof AppAffiliatedMembersRoute
  '/manage/persons': typeof AppManagePersonsRoute
  '/my-groups/$groupId': typeof AppMyGroupsGroupIdRoute
  '/my-groups/': typeof AppMyGroupsIndexRoute
  '/groups/$groupId': typeof AppAffiliatedGroupsGroupIdRoute
  '/members/$personId': typeof AppAffiliatedMembersPersonIdRoute
  '/manage/persons/$personId': typeof AppManagePersonsPersonIdRoute
}
export interface FileRoutesByTo {
  '/login': typeof LoginRoute
  '/': typeof AppIndexRoute
  '/profile': typeof AppProfileRoute
  '/groups': typeof AppAffiliatedGroupsRoute
  '/members': typeof AppAffiliatedMembersRoute
  '/manage/persons': typeof AppManagePersonsRoute
  '/my-groups/$groupId': typeof AppMyGroupsGroupIdRoute
  '/my-groups': typeof AppMyGroupsIndexRoute
  '/groups/$groupId': typeof AppAffiliatedGroupsGroupIdRoute
  '/members/$personId': typeof AppAffiliatedMembersPersonIdRoute
  '/manage/persons/$personId': typeof AppManagePersonsPersonIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_app': typeof AppRouteWithChildren
  '/login': typeof LoginRoute
  '/_app/_affiliated': typeof AppAffiliatedRouteWithChildren
  '/_app/profile': typeof AppProfileRoute
  '/_app/': typeof AppIndexRoute
  '/_app/_affiliated/groups': typeof AppAffiliatedGroupsRoute
  '/_app/_affiliated/members': typeof AppAffiliatedMembersRoute
  '/_app/manage/persons': typeof AppManagePersonsRoute
  '/_app/my-groups/$groupId': typeof AppMyGroupsGroupIdRoute
  '/_app/my-groups/': typeof AppMyGroupsIndexRoute
  '/_app/_affiliated/groups_/$groupId': typeof AppAffiliatedGroupsGroupIdRoute
  '/_app/_affiliated/members_/$personId': typeof AppAffiliatedMembersPersonIdRoute
  '/_app/manage/persons_/$personId': typeof AppManagePersonsPersonIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/profile'
    | '/groups'
    | '/members'
    | '/manage/persons'
    | '/my-groups/$groupId'
    | '/my-groups/'
    | '/groups/$groupId'
    | '/members/$personId'
    | '/manage/persons/$personId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/login'
    | '/'
    | '/profile'
    | '/groups'
    | '/members'
    | '/manage/persons'
    | '/my-groups/$groupId'
    | '/my-groups'
    | '/groups/$groupId'
    | '/members/$personId'
    | '/manage/persons/$personId'
  id:
    | '__root__'
    | '/_app'
    | '/login'
    | '/_app/_affiliated'
    | '/_app/profile'
    | '/_app/'
    | '/_app/_affiliated/groups'
    | '/_app/_affiliated/members'
    | '/_app/manage/persons'
    | '/_app/my-groups/$groupId'
    | '/_app/my-groups/'
    | '/_app/_affiliated/groups_/$groupId'
    | '/_app/_affiliated/members_/$personId'
    | '/_app/manage/persons_/$personId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AppRoute: typeof AppRouteWithChildren
  LoginRoute: typeof LoginRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/': {
      id: '/_app/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/profile': {
      id: '/_app/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof AppProfileRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/_affiliated': {
      id: '/_app/_affiliated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppAffiliatedRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/my-groups/': {
      id: '/_app/my-groups/'
      path: '/my-groups'
      fullPath: '/my-groups/'
      preLoaderRoute: typeof AppMyGroupsIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/my-groups/$groupId': {
      id: '/_app/my-groups/$groupId'
      path: '/my-groups/$groupId'
      fullPath: '/my-groups/$groupId'
      preLoaderRoute: typeof AppMyGroupsGroupIdRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/manage/persons': {
      id: '/_app/manage/persons'
      path: '/manage/persons'
      fullPath: '/manage/persons'
      preLoaderRoute: typeof AppManagePersonsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/_affiliated/members': {
      id: '/_app/_affiliated/members'
      path: '/members'
      fullPath: '/members'
      preLoaderRoute: typeof AppAffiliatedMembersRouteImport
      parentRoute: typeof AppAffiliatedRoute
    }
    '/_app/_affiliated/groups': {
      id: '/_app/_affiliated/groups'
      path: '/groups'
      fullPath: '/groups'
      preLoaderRoute: typeof AppAffiliatedGroupsRouteImport
      parentRoute: typeof AppAffiliatedRoute
    }
    '/_app/manage/persons_/$personId': {
      id: '/_app/manage/persons_/$personId'
      path: '/manage/persons/$personId'
      fullPath: '/manage/persons/$personId'
      preLoaderRoute: typeof AppManagePersonsPersonIdRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/_affiliated/members_/$personId': {
      id: '/_app/_affiliated/members_/$personId'
      path: '/members/$personId'
      fullPath: '/members/$personId'
      preLoaderRoute: typeof AppAffiliatedMembersPersonIdRouteImport
      parentRoute: typeof AppAffiliatedRoute
    }
    '/_app/_affiliated/groups_/$groupId': {
      id: '/_app/_affiliated/groups_/$groupId'
      path: '/groups/$groupId'
      fullPath: '/groups/$groupId'
      preLoaderRoute: typeof AppAffiliatedGroupsGroupIdRouteImport
      parentRoute: typeof AppAffiliatedRoute
    }
  }
}

interface AppAffiliatedRouteChildren {
  AppAffiliatedGroupsRoute: typeof AppAffiliatedGroupsRoute
  AppAffiliatedMembersRoute: typeof AppAffiliatedMembersRoute
  AppAffiliatedGroupsGroupIdRoute: typeof AppAffiliatedGroupsGroupIdRoute
  AppAffiliatedMembersPersonIdRoute: typeof AppAffiliatedMembersPersonIdRoute
}

const AppAffiliatedRouteChildren: AppAffiliatedRouteChildren = {
  AppAffiliatedGroupsRoute: AppAffiliatedGroupsRoute,
  AppAffiliatedMembersRoute: AppAffiliatedMembersRoute,
  AppAffiliatedGroupsGroupIdRoute: AppAffiliatedGroupsGroupIdRoute,
  AppAffiliatedMembersPersonIdRoute: AppAffiliatedMembersPersonIdRoute,
}

const AppAffiliatedRouteWithChildren = AppAffiliatedRoute._addFileChildren(
  AppAffiliatedRouteChildren,
)

interface AppRouteChildren {
  AppAffiliatedRoute: typeof AppAffiliatedRouteWithChildren
  AppProfileRoute: typeof AppProfileRoute
  AppIndexRoute: typeof AppIndexRoute
  AppManagePersonsRoute: typeof AppManagePersonsRoute
  AppMyGroupsGroupIdRoute: typeof AppMyGroupsGroupIdRoute
  AppMyGroupsIndexRoute: typeof AppMyGroupsIndexRoute
  AppManagePersonsPersonIdRoute: typeof AppManagePersonsPersonIdRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppAffiliatedRoute: AppAffiliatedRouteWithChildren,
  AppProfileRoute: AppProfileRoute,
  AppIndexRoute: AppIndexRoute,
  AppManagePersonsRoute: AppManagePersonsRoute,
  AppMyGroupsGroupIdRoute: AppMyGroupsGroupIdRoute,
  AppMyGroupsIndexRoute: AppMyGroupsIndexRoute,
  AppManagePersonsPersonIdRoute: AppManagePersonsPersonIdRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AppRoute: AppRouteWithChildren,
  LoginRoute: LoginRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
